[tool.poetry]
name = "monitoring-kubernetes"
version = "0.1.0"
description = "kubernetes monitoring tool using python kubernetes library"
authors = ["KKamJi <xowl5460@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.14"
kubernetes = "^32.0.0"
tabulate = "^0.9.0"



[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
