[tool.poetry]
name = "monitoring-kubernetes"
version = "0.1.0"
description = "monitoring kubernetes with python"
authors = ["KKamJi <xowl5460@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8"
kubernetes = "^32.0.1"
tabulate = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
