name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install uv
        run: pip install uv
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install .
      - name: Install dev dependencies
        run: uv pip install ".[dev]"
      - name: Run Black
        run: black . --check
      - name: Run Ruff
        run: ruff . --fix --exit-non-zero-on-fix
      - name: Run MyPy
        run: mypy .
      - name: Run tests with Pytest and Pytest-Cov
        run: pytest --cov=./ --cov-report=xml

  release-please:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: python
          package-name: monitoring-kubernetes
