name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install uv
        run: pip install uv
      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install .
          uv pip install ".[dev]"
      - name: Run Ruff Format (check)
        run: |
          source .venv/bin/activate
          ruff format --check .
      - name: Run Ruff
        run: |
          source .venv/bin/activate
          ruff check . --fix --exit-non-zero-on-fix
      - name: Run MyPy
        run: |
          source .venv/bin/activate
          mypy .
      - name: Run tests with Pytest and Pytest-Cov
        run: |
          source .venv/bin/activate
          pytest --cov=./ --cov-report=xml

  release-please:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: python
          package-name: monitoring-kubernetes
